# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(System.DefaultWorkingDirectory)/PreMed/PreMed.csproj'
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Visual Studio Enterprise Ultimate Subscription(e9d2e652-4321-4316-a8b2-2a2130d54818)'
#     appType: 'webAppLinux'
#     appName: 'tools-premed'
#     package: '/**/*.zip'
#     runtimeStack: 'DOTNETCORE|7.0'
